apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name}}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32042
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 32043