name: Integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go version
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-username: user
          mongodb-password: password
          mongodb-db: dora
      - name: Test
        run: |
          go install github.com/onsi/ginkgo/ginkgo 
          ginkgo -r -v